import { ArrowRight } from 'lucide-react';
import Link from 'next/link';
import { ArticleGrid, CTA, Kicker, Newsletter, PageIntro, Reveal, Section } from '@/components/marketing/marketing';
const items=[
  {date:'Sep 10, 2026',category:'FIELD NOTE',title:'One million carbon credits to cut methane emissions and save water',href:'/insights/one-million-carbon-credits-to-eliminate-methane-and-save-water'},
  {date:'Aug 15, 2026',category:'WATER',title:"Why rice irrigation matters: a look at India's 2026 water crisis",href:'/insights/why-rice-irrigation-matters-a-look-at-indias-2026-water-crisis'},
  {date:'Aug 5, 2026',category:'CLIMATE-SMART RICE',title:"Mitti Labs raises $9.5M to build water resilience in Asia's rice fields",href:'/insights/mitti-labs-raises-9.5m-to-build-water-resilience-in-asia-s-rice-ields'},
  {date:'Jul 28, 2026',category:'CARBON CREDITS',title:"Sylvera issues an 'A' Rating for Mitti Labs' carbon credits based on rice methane",href:'/insights/sylvera-rating'},
  {date:'Jul 15, 2026',category:'MRV',title:'Leveraging technology for traceable impact: our first carbon credit issuance',href:'/insights/leveraging-technology-for-trackeable-impact'},
  {date:'Jun 19, 2026',category:'SCIENCE',title:'Beyond CO₂: Carbon Direct X Mitti Labs',href:'/insights/carbon-direct-x-mitti-labs-beyond-co2-webinar'},
  {date:'May 18, 2026',category:'CLIMATE',title:'The other half of global warming, and what we can do about it',href:'/insights/the-other-half-of-global-warming-%E2%80%94-and-what-we-can-do-about-it'},
  {date:'May 13, 2026',category:'METHANE',title:'Cool Effect and Mitti Labs: partnering on a world first for superpollutant credits based on rice methane reduction',href:'/insights/cool-effect-and-mitti-labs-partnering-on-a-world-first'},
  {date:'Mar 27, 2026',category:'CARBON MARKETS',title:'An update from ICVCM: Rice methane gets its Core Carbon Principles label',href:'/insights/an-update-from-icvcm-rice-methane-gets-its-core-carbon-principle-label'},
  {date:'Feb 10, 2026',category:'RESEARCH',title:"Mitti Labs partners with ICAR-IARI, India's leading institution for scientific innovation in agriculture",href:'/insights/mitti-labs-and-icar-iari-partner-on-ground-breaking-research-to-quantify-methane-emissions-from-rice-farming'},
  {date:'Dec 3, 2025',category:'FIELD PARTNERSHIPS',title:'ACCESS and Mitti Labs: a partnership to transform rice farming in India',href:'/insights/mitti-labs-and-access-are-transforming-rice-farming-in-india'},
  {date:'Nov 21, 2025',category:'CLIMATE',title:'The future of rice: is climate change reshaping India’s monsoon?',href:'/insights/the-future-of-rice-is-climate-change-reshaping-india-s-monsoon'},
  {date:'Nov 13, 2025',category:'FAQ',title:'Mitti Labs: Frequently Asked Questions',href:'/insights/frequently-asked-questions'},
  {date:'Sep 26, 2025',category:'WATER',title:'Every drop counts: how farmers protect India’s water future with Alternate Wetting and Drying',href:'/insights/every-drop-counts-how-farmers-and-mitti-labs-are-protecting-india-s-water-future'}
];
export default function Insights(){return <main className="c4n-root"><PageIntro eyebrow="/ INSIGHTS" title={<>Insights<br/><em>from soil to sky.</em></>} description="Notes on rice, methane, water, remote sensing, digital MRV and carbon economics." visual="satellite"/><Section kicker="THE LATEST" title={<>Keep exploring.</>}><ArticleGrid items={items.slice(0,3)}/></Section><section className="c4n-section c4n-section-paper"><div className="c4n-container"><Reveal className="c4n-feature-article"><div className="c4n-feature-art"><div className="c4n-feature-art-grid"/><span>FEATURED INSIGHT</span></div><div><Kicker>FEATURED INSIGHT</Kicker><h3>One million carbon credits to cut methane emissions and save water.</h3><p>Explore the latest work on rice methane reduction, water savings, Alternate Wetting and Drying, and field-level climate intelligence.</p><Link href="/insights/one-million-carbon-credits-to-eliminate-methane-and-save-water" className="c4n-inline-link">Read the featured insight <ArrowRight size={15}/></Link></div></Reveal></div></section><Section kicker="ALL INSIGHTS" title={<>More from<br/><em>Code4Nature.</em></>}><ArticleGrid items={items.slice(3)}/></Section><div className="c4n-container"><Newsletter/></div><CTA title="Turn the next field note into a field experiment."/></main>}
