from .carbon_model import potential_credits,gross_value_usd
from .methane_model import emission_model
from .revenue_model import allocate
from .water_model import water_model
from .providers import timestamp
MODEL_VERSION="demo-v1.0"
def calculate_simulation(*,area_ha:float,soil_type:str,season:str,crop_duration_days:int,management_type:str,baseline_water_liters:float,rainfall_assumption_mm:float,baseline_emission_tco2e_per_ha:float,reduction_percent:float,carbon_price_usd:float,farmer_share:float,company_share:float,fx_rate:float=83.0):
    water=water_model.predict(area_ha=area_ha,soil_type=soil_type,crop_duration_days=crop_duration_days,season=season,baseline_irrigation_liters=baseline_water_liters,rainfall_assumption_mm=rainfall_assumption_mm,management_type=management_type)
    baseline_total=emission_model.predict_baseline(area_ha,baseline_emission_tco2e_per_ha); project_total=emission_model.predict_project(area_ha,baseline_emission_tco2e_per_ha,reduction_percent); reduction=emission_model.calculate_reduction(baseline_total,project_total); credits=potential_credits(reduction); gross=gross_value_usd(credits,carbon_price_usd); farmer_revenue,company_revenue=allocate(gross,farmer_share,company_share)
    return {"model_version":MODEL_VERSION,"timestamp":timestamp(),"data_source":"synthetic_demo","data_type":"simulated","farm_area_ha":round(area_ha,4),"baseline_water_liters":round(water.baseline_liters,2),"project_water_liters":round(water.project_liters,2),"water_saved_liters":round(water.water_saved_liters,2),"water_saving_percent":round(water.water_saving_percent,2),"baseline_emission_tco2e_per_ha":round(baseline_emission_tco2e_per_ha,4),"project_emission_tco2e_per_ha":round(baseline_emission_tco2e_per_ha*(1-max(0,min(70,reduction_percent))/100),4),"baseline_emission_total_tco2e":round(baseline_total,4),"project_emission_total_tco2e":round(project_total,4),"emission_reduction_tco2e":round(reduction,4),"reduction_percent":round(max(0,min(70,reduction_percent)),2),"potential_credits":round(credits,4),"carbon_price_usd":round(carbon_price_usd,4),"gross_value_usd":round(gross,2),"usd_inr_rate":round(fx_rate,4),"gross_value_inr":round(gross*fx_rate,2),"farmer_share_percent":round(farmer_share,2),"company_share_percent":round(company_share,2),"farmer_revenue_usd":round(farmer_revenue,2),"farmer_revenue_inr":round(farmer_revenue*fx_rate,2),"company_revenue_usd":round(company_revenue,2),"company_revenue_inr":round(company_revenue*fx_rate,2)}